# Generated by Django 3.2.23 on 2025-05-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=100)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('rack_id', models.CharField(max_length=100)),
                ('retail_price', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
    ]
